vich_uploader:
    db_driver: orm

    mappings:
       announces:
           uri_prefix: /images/announces
           upload_destination: '%kernel.project_dir%/public/images/announces'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       profilePicture:
           uri_prefix: /images/profile
           upload_destination: '%kernel.project_dir%/public/images/profile'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

